# Generated by Django 5.2 on 2025-04-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='user',
        ),
        migrations.AddField(
            model_name='favorite',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
